### ISSUE TITLE
Gmail OAuth2 Support

### ISSUE THREAD

**Issue by neebish** [jimlawless/mailwrench#1]
Jim,

Gmail is shifting away from allowing user/password, and only allowing OAuth token support for their service.  Do you have any plans to implement OAuth token support in this application?

**Comment by jimlawless** [comment]
Mailwrench is not software that I support in an ongoing fashion.

However, I believe that you'll still be able to use a Google App Password
even once everything is OAuth.  You might take a look at the steps outlined
in this page: https://support.google.com/accounts/answer/185833?hl=en

Once you generate the app password on the device that will be using it, you
should be able to use the normal Gmail ID with the newly generated app
password.
